### ISSUE TITLE
sharing changes between sessions does not work

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [miguelgrinberg/Flask-SocketIO#1071]
Hey, I want to play around with websockets in Flask a bit, to have a demo for a  friend, so I wrote the following code:
```Python
from flask import Flask, send_from_directory, render_template, session, request, url_for
from flask_session import Session
from flask_socketio import SocketIO

app = Flask(__name__)
app.config["SECRET_KEY"] = "SECRET"
app.config['SESSION_TYPE'] = 'filesystem'
Session(app)
sock = SocketIO(app, manage_session=False)


client_dict = {
    "1": "W",
    "2": "Ich BinEinAnderesPasswort"
}

socket_dict = {}



@sock.on("logout")
def logout():
    print(dict(session))
    if "client_id" in session:
        if session["client_id"] in socket_dict:
            del socket_dict["client_id"]
    session.clear()
    print(dict(session))
    sock.emit("response", {"logout": {"success": True, "url": url_for("get_login")}})


@sock.on("login")
def login(msg):
    print(dict(session))
    return_data: dict = {}
    client_id = msg.get("id")
    password = msg.get("password")
    if client_id in ["", None] or password in ["", None]:
        return_data = {"Error": "Missing credentials"}
    else:
        if client_id in client_dict:
            if client_id in socket_dict:
                return_data = {"Error": "Already logged in"}
            elif client_dict[client_id] == password:
                return_data = {"success": True, "url": url_for("client")}
                session["client_id"] = client_id
                socket_dict.update({client_id: request.sid})
            else:
                return_data = {"Error": "Invalid credentials"}
    print(dict(session))
    sock.emit("response", {"login": return_data})


@app.route("/login")
def get_login():
    print(dict(session))
    return render_template("client_login.html")


@app.route('/')
def index():
    return render_template("index.html")


@app.route("/client")
def client():
    print(dict(session))
    if "client_id" in session:
        client_id = session["client_id"]
        return render_template("client.html", client_id=client_id)
    else:
        return "You must login first: <a href='/login'>Login</a>"


if __name__ == '__main__':
    sock.async_mode = True
    sock.run(app=app, debug=True)
```

After login, the session variable within the login scope contains "client_id" like this: 
`{'_permanent': True, 'client_id': '1'}`
but on regular Flask routes, the session does not:
`{'_permanent': True}`
What am I doing wrong?

**Comment by miguelgrinberg** [comment]
Have you verified that the sessions are working? For example, if you set something in a Flask HTTP route, is it remembered when the same or another HTTP route is invoked? The most likely explanation for your problem is that the sessions aren't being written to disk.

**Comment by TheCataliasTNT2k** [comment]
Yes, this is working. Only the communication between http and socketio is not working as described.

**Comment by miguelgrinberg** [comment]
@TheCataliasTNT2k Okay. Can I ask you to run a simple test? In your `login()` function, change the print statement one line before the end of the function to this:

    print(session.modified)

If you get `False`, then that's the problem, Flask-Session is not detecting that you are changing the session, so Flask-SocketIO does not know that it needs to be saved. In that case, you can add a `session.modified = True` right where the print statement is, and that I think should fix this.

**Comment by TheCataliasTNT2k** [comment]
Ok, I tested a few things:
On `app.route` (e.g. `login` or `client`) `session.modified` is `False` after login completes, but setting it to `True` does not fix it, the session is still empty.
Within the socket login function, the session is displayed with correct values, and `session.modified` is `True`as well...

**Comment by miguelgrinberg** [comment]
You are doing more than what I ask and are mixing too many things at once. Remove all references to `session.modified` in your code, then modify the `print(dict(session))` in the line before last of function `login()` to:

    print(session.modified)

Does this print `True`, `False`, or do you get an attribute error?

**Comment by TheCataliasTNT2k** [comment]
It prints `False`

**Comment by miguelgrinberg** [comment]
Right. So you see the problem? If you add something to the session, but the session object does not mark itself as modified, then those changes are not going to be saved. If you set `session.modified = True` before returning from the `login()` function, then the session will be saved.

**Comment by TheCataliasTNT2k** [comment]
this is my login function, I set `session.modified` to `True` now
```Python

@sock.on("login")
def login(msg):
    print(dict(session))
    return_data: dict = {}
    client_id = msg.get("id")
    password = msg.get("password")
    if client_id in ["", None] or password in ["", None]:
        return_data = {"Error": "Missing credentials"}
    else:
        if client_id in client_dict:
            if client_id in socket_dict:
                return_data = {"Error": "Already logged in"}
            elif client_dict[client_id] == password:
                return_data = {"success": True, "url": url_for("client")}
                session["client_id"] = client_id
                socket_dict.update({client_id: request.sid})
                session.modified = True
            else:
                return_data = {"Error": "Invalid credentials"}
    print(dict(session))
    sock.emit("response", {"login": return_data})
                return_data = {"Error": "Already logged in"}
            elif drone_dict[drone_id] == password:
                return_data = {"success": True, "url": url_for("client")}
                session["drone_id"] = drone_id
                socket_dict.update({drone_id: request.sid})
                session.modified = True
            else:
                return_data = {"Error": "Invalid credentials"}
    print(dict(session))
    sock.emit("response", {"login": return_data})
```
this is the login flask route, to get to the other login page (websocket):
```Python
@app.route("/login")
def get_login():
    print(dict(session))
    return render_template("client_login.html")
```
It is still printing `False`

**Comment by miguelgrinberg** [comment]
> It is still printing False

What is still printing `False`? If you are talking about `session.modified`, this boolean attribute is reset back to `False` when a new request or Socket.IO event are invoked.

**Comment by TheCataliasTNT2k** [comment]
Ok, that is nice to know.
But if I request /login or /client, the session is still empty.

**Comment by miguelgrinberg** [comment]
@TheCataliasTNT2k I don't honestly see how can this not work, since this is all based on standard session functions from Flask. It would not work only if your custom session has bugs (as we've seen in the `modified` flag not being correctly implemented) or if you are using the session in the wrong way.

The session must be created by an HTTP route. Have you done that? Socket.IO events cannot set cookies in the client, so the session must already exist when the connection to Socket.IO is made. Maybe that's your misunderstanding?

**Comment by TheCataliasTNT2k** [comment]
The session is created by visiting the / or /login Flask route. But you can try the code yourself, and see, if it works for you.
It is fairly simple:
The client should login first and then it can connect to /client.
You can find my complete code [here](https://github.com/TheCataliasTNT2k/websocket-demo).

**Comment by miguelgrinberg** [comment]
You are not creating a user session in the HTTP routes, as far as I can see.

**Comment by TheCataliasTNT2k** [comment]
Well, I have a session in my browser cache, if I request a Flask route... Does Flask not create a session automatically if you request a Flask route?

**Comment by miguelgrinberg** [comment]
A session is only created if you access the session variable explicitly in
the route.

**Comment by TheCataliasTNT2k** [comment]
```@app.route('/')
def hello_world():
    session["xy"] = 1
    return render_template("index.html")```
changed that in my code, still no login... deleted all session in flask-session directory and browser as well...

**Comment by miguelgrinberg** [comment]
@TheCataliasTNT2k You need to be more specific about what is it that is not working as you expect. When the `/` route creates the session and then the login event handler adds the id to it, this id is accessible in subsequent routes such as `/client`. So as far as I can see, your app is working well.

**Comment by miguelgrinberg** [comment]
I understand what you are saying, but when I run your code here I don't see the problem. Here is my output:

```
(venv) websocket-demo $ python app.py                                                                                                 *master
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Debugger is active!
 * Debugger PIN: 199-706-761
127.0.0.1 - - [16/Oct/2019 18:10:53] "GET /socket.io/?EIO=3&transport=polling&t=MtLZGoT HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2019 18:10:56] "GET / HTTP/1.1" 200 -
{'_permanent': True, 'xy': 1}
127.0.0.1 - - [16/Oct/2019 18:11:02] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2019 18:11:02] "GET /socket.io/?EIO=3&transport=polling&t=MtLZJ0L HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2019 18:11:10] "POST /socket.io/?EIO=3&transport=polling&t=MtLZKy5&sid=d1351decb8904a32b184f0a6231c37bd HTTP/1.1" 200 -
{'_permanent': True, 'xy': 1}
{'_permanent': True, 'xy': 1, 'client_id': '1'}
127.0.0.1 - - [16/Oct/2019 18:11:10] "GET /socket.io/?EIO=3&transport=polling&t=MtLZGob&sid=37cb0620063446e4826b7518a5571556 HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2019 18:11:10] "GET /socket.io/?EIO=3&transport=polling&t=MtLZJ0c&sid=d1351decb8904a32b184f0a6231c37bd HTTP/1.1" 200 -
False
{'_permanent': True, 'xy': 1, 'client_id': '1'}
127.0.0.1 - - [16/Oct/2019 18:11:10] "GET /client HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2019 18:11:10] "GET /socket.io/?EIO=3&transport=polling&t=MtLZKzF HTTP/1.1" 200 -
False
{'_permanent': True, 'xy': 1, 'client_id': '1'}
127.0.0.1 - - [16/Oct/2019 18:11:25] "GET /client HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2019 18:11:25] "GET /socket.io/?EIO=3&transport=polling&t=MtLZOdh HTTP/1.1" 200 -
False
{'_permanent': True, 'xy': 1, 'client_id': '1'}
127.0.0.1 - - [16/Oct/2019 18:11:26] "GET /client HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2019 18:11:26] "GET /socket.io/?EIO=3&transport=polling&t=MtLZOp0 HTTP/1.1" 200 -
False
{'_permanent': True, 'xy': 1, 'client_id': '1'}
127.0.0.1 - - [16/Oct/2019 18:11:27] "GET /client HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2019 18:11:27] "GET /socket.io/?EIO=3&transport=polling&t=MtLZOwt HTTP/1.1" 200 -
```

Here I went to `/`, then clicked on the login link. The Socket.IO connection was made at that point. I logged in with user `1` and password `W`. After that, I was sent to `/client`. I refreshed that page a few times, and you can see that the console is printing the `client_id` in all these refreshes. So this is working fine.

**Comment by TheCataliasTNT2k** [comment]
Ok, tried to reproduce your steps as exactly as possiblee:
```
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 159-716-676
(26143) wsgi starting up on http://127.0.0.1:5000
(26143) accepted ('127.0.0.1', 35838)
127.0.0.1 - - [17/Oct/2019 00:30:16] "GET / HTTP/1.1" 200 462 0.015269
{'_permanent': True, 'xy': 1}
127.0.0.1 - - [17/Oct/2019 00:30:30] "GET /login HTTP/1.1" 200 945 0.009707
127.0.0.1 - - [17/Oct/2019 00:30:30] "GET /static/socket_lib.js HTTP/1.1" 200 1220 0.021737
(26143) accepted ('127.0.0.1', 35842)
127.0.0.1 - - [17/Oct/2019 00:30:30] "GET /static/socket.io.js HTTP/1.1" 304 377 0.003117
(26143) accepted ('127.0.0.1', 35846)
127.0.0.1 - - [17/Oct/2019 00:30:30] "GET /socket.io/?EIO=3&transport=polling&t=MtMiQhw HTTP/1.1" 200 401 0.001191
(26143) accepted ('127.0.0.1', 35848)
127.0.0.1 - - [17/Oct/2019 00:30:31] "GET /socket.io/?EIO=3&transport=polling&t=MtMiQk_&sid=8e7df6c60674498badac86a118bd5fc0 HTTP/1.1" 200 235 0.035429
{'_permanent': True}
{'_permanent': True, 'client_id': '1'}
127.0.0.1 - - [17/Oct/2019 00:31:33] "GET /socket.io/?EIO=3&transport=websocket&sid=8e7df6c60674498badac86a118bd5fc0 HTTP/1.1" 200 0 62.141372
False
{'_permanent': True, 'xy': 1}
127.0.0.1 - - [17/Oct/2019 00:31:33] "GET /client HTTP/1.1" 200 303 0.001556
False
{'_permanent': True, 'xy': 1}
127.0.0.1 - - [17/Oct/2019 00:31:56] "GET /client HTTP/1.1" 200 303 0.009180
False
{'_permanent': True, 'xy': 1}
127.0.0.1 - - [17/Oct/2019 00:31:57] "GET /client HTTP/1.1" 200 303 0.001781
False
{'_permanent': True, 'xy': 1}
127.0.0.1 - - [17/Oct/2019 00:31:59] "GET /client HTTP/1.1" 200 303 0.001621
False
{'_permanent': True, 'xy': 1}
127.0.0.1 - - [17/Oct/2019 00:32:00] "GET /client HTTP/1.1" 200 303 0.002254
False
{'_permanent': True, 'xy': 1}
127.0.0.1 - - [17/Oct/2019 00:32:00] "GET /client HTTP/1.1" 200 303 0.004782```
I noticed the following differences:
1. I do not establish a socket connection on / or /client as you do. Do I need to do that? Because I do not need the connection at that point, I did not include socketio in my html for that pages.
2. I only get
 `"GET /socket.io/?EIO=3&transport=polling&t=MtLZJ0c&sid=d1351decb8904a32b184f0a6231c37bd HTTP/1.1" 200 -`
 regarding to sockets, but not
 `"POST /socket.io/?EIO=3&transport=polling&t=MtLZKy5&sid=d1351decb8904a32b184f0a6231c37bd HTTP/1.1" 200 -`
as you do.
So what are the differences in our codes, and do I need to include socketio in all pages?

**Comment by dist1** [comment]
Something similar on here!

It seems that the setback on @socket.on will no taken on @app.route ...

Is it possible from the front-end ? For example, how the .html file is .

I cannot resolve this as much.

**Comment by miguelgrinberg** [comment]
@dist1 are you using the standard Flask sessions? That's expected, see the [documentation](https://flask-socketio.readthedocs.io/en/latest/#access-to-flask-s-context-globals).

**Comment by dist1** [comment]
...

However, I change to use the flask_session

```python
from flask_session import Session
#...
app.config['SESSION_TYPE'] = 'filesystem'
Session(app)
```

And it works.

**Comment by dist1** [comment]
@miguelgrinberg I try to debugging on the source.. but I finally cannot understand anything... evently `where the value actually write into some data container` ...

I see that there are a var `self.server.envrion[sid]` , but however when I print it out, it's value is `None`  ...

bless all...

**Comment by TANMAY007100** [comment]
Hi @miguelgrinberg, 

I was trying Flask-SocketIO and facing issue related to Redis session getting empty sessions in SocketIO events even after using server side session by Flask-Session.

Now first I thought I am doing something wrong but the way I see it seems the library doesn't work only in Windows since I tried in a Cloud VM running Ubuntu 18.04. It runs well.

Here's my code:

__init__.py:

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_session import Session

import redis

from flask_socketio import SocketIO

socketio = SocketIO()

from .models import db, User

def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__, static_url_path='/static', 
            static_folder='static')
    app.config["SQLALCHEMY_DATABASE_URI"] = 'sqlite:///db.sqlite3'
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.config['SECRET_KEY'] = 'secretkey'
    app.config["SESSION_TYPE"] = 'redis'
    
    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    Session(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    app.debug = debug
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    socketio.init_app(app, manage_session=False, cors_allowed_origins='*', message_queue='amqp://')
    return app
```
events.py:

```
from flask_socketio import send, emit, join_room, leave_room
from flask import request, session
from .. import socketio
from flask_login import current_user

@socketio.on('message')
def connected(message):
    # I am getting the message and sid correctly so no problem there.
    # Here I get <RedisSession {'_permanent': True}> that's it
    print (session) 
    # Here I get <flask_login.mixins.AnonymousUserMixin object at ...............>
    print (current_user)
    send(message, broadcast=True)

@socketio.on('message')
def message(message):
    # Same problem here
    send(message, broadcast=True)
```

models.py:
```
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(UserMixin, db.Model):

    __tablename__ = "user"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True)
    username = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(100))
    socket_sid = db.Column(db.String(255))
```

chat.py:
```
from app import create_app, socketio
from gevent import monkey
monkey.patch_all()

app = create_app(debug=True)

if __name__ == '__main__':
    socketio.run(app)
```

chat.html:
```
<body>
    <ul id="messages">
    </ul>
    <input id="message" type="text" />
    <input id="sendMessage" type="submit" value="Submit">
    <script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"
        integrity="sha256-bQmrZe4yPnQrLTY+1gYylfNMBuGfnT/HKsCGX+9Xuqo=" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</body>
```


scripts.js:
```
$(document).ready(function () {
    var socket = io.connect('http://127.0.0.1:5000');

    socket.on('connect', function() {
        socket.send("Connected");
        $("#messages").append("Client connected");
    })

    socket.on('message', function(msg) {
        $("#messages").append('<li>'+msg+'</li>');
    })

    $("#sendMessage").on('click', function() {
        socket.emit('send_message', $("#message").val());
        $("#message").val('');
    });

    socket.on('disconnect', () => {
        socket.send('user disconnected');
    });
});
```

routes.py:

```
from flask import session, redirect, url_for, render_template, request
from . import auth
from .forms import LoginForm, RegisterForm

from werkzeug.security import generate_password_hash, check_password_hash

from flask_login import login_user, logout_user

from .. import db
from ..models import User


@auth.route('/login', methods=["GET"])
def login():
    login_form = LoginForm()
    return render_template('login.html', login_form=login_form)

@auth.route('/login', methods=["POST"])
def login_post():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        username = login_form.username.data
        remember_me = login_form.remember_me.data
        get_user = User.query.filter_by(username=username).first()
        check_password_hash(get_user.password, login_form.password.data)
        login_user(get_user, remember=remember_me)
        session["current_user"] = get_user.id
        # Here I do get session.modified as True
        print (session.modified)
        return redirect(url_for('main.home'))

@auth.route('/register', methods=["GET"])
def register():
    register_form = RegisterForm()
    return render_template('register.html', register_form=register_form)

@auth.route('/register', methods=["POST"])
def register_post():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        name = register_form.name.data
        email = register_form.email.data
        username = register_form.username.data
        password = register_form.password.data
        create_user = User(
            name=name,
            email=email,
            username=username,
            password=generate_password_hash(password,method="sha256")
        )
        db.session.add(create_user)
        db.session.commit()
        return redirect(url_for("main.home"))
    else:
        print (register_form.errors)
    return render_template('register.html', register_form=register_form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@auth.route('/chat')
def chat():
    # Here I do get modified session like so:
    # <RedisSession {'_permanent': True, 'xy': 1, '_fresh': True, 'csrf_token': 'd9c0a4b01bb051395ff8a105230d47140495df19', '_user_id': '3', '_id': 'b53efba6dd9143dac799d8a3a41cfe0eb840180579737f6730fea787562df946c56ebcd1a3deaf68ce5227c446d60e788cab5185bbd8e313b7e776ee36bc3916', 'current_user': 3}>
    print ("session", session)
    return render_template('chat.html')
```

**What I tried:**

1. Flask-Session with Redis and RabbitMQ on my Windows machine.
2. Provisioned a VM on Cloud (Ubuntu 18.04) and ran the same thing there under gunicorn where not only it is working but also giving current_user inside the SocketIO events.
3. Flask-KVSession library which also works in ubuntu and not in Windows.

**Packages Versions in Windows:**

amqp==2.5.2
Flask==1.1.2
Flask-KVSession==0.6.2
Flask-Login==0.5.0
Flask-Session==0.3.1
Flask-SocketIO==4.3.0
Flask-SQLAlchemy==2.4.1
python-engineio==3.12.1
python-socketio==4.5.1
redis==3.4.1
SQLAlchemy==1.3.16
Werkzeug==1.0.1

Can you suggest a solution to this?

**Comment by miguelgrinberg** [comment]
@TANMAY007100 do I understand it right that this only fails to work on Windows? If that's the case, then it would be hard to tell, but a lot of code isn't written with Windows in mind, so any of the dependencies can be at fault here.

If you wanted to get to the bottom of this you would need to debug this by looking at cookies and contents of your Redis db to see where is the session dropped.

**Comment by Joe-ChenZ** [comment]
Hi Miguel,

I was following this tutorial to share sessions between the http and socketio using this blog:
https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session

Things were working until i upgraded my Flask from 2 to 3, Flask-SocketIO from 2.0.1 to 5.4.1.

This is my configuration setup:

```
app.config.update(
    SESSION_TYPE="redis",
    SESSION_USE_SIGNER=True,
    SESSION_REDIS=flask_session_redis_client,
    SESSION_FILE_THRESHOLD=10000,
    PERMANENT_SESSION_LIFETIME=timedelta(days=1),
    SESSION_COOKIE_SECURE=True,
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE="None" if args.debug else "Lax",
)

Session(app)

 socketio = SocketIO(
        app,
        async_mode="gevent",
        cors_allowed_origins="*",
        manage_session=False,
        message_queue=get_transport_url(),
        client_manager=mgr,
        channel="socketio_mgr",
)
```

**Comment by miguelgrinberg** [comment]
@Joe-ChenZ a working example is included in this repository. Start from that example and modify it according to your needs.

**Comment by Joe-ChenZ** [comment]
I couldn't quite tell what i did was wrong. But it seems that it requires some http requests before the socketio to set the `session`. Then the socketio can use the session and append more data to it. Seems like whenever I let socketio set the session first, the subsequent http requests don't get the same session, even after I refresh the browser

**Comment by Joe-ChenZ** [comment]
https://stackoverflow.com/questions/73492924/flask-session-session-not-saving-inside-a-flask-socketio-websocket-request This is the issue I am having. I am doing the way this post does as a temporary fix, but I am not sure what the issue is. Adding a random field in the `@app.before_request` fixes everything.

**Comment by miguelgrinberg** [comment]
@Joe-ChenZ A session can only be set in an HTTP route. Creating a session involves sending a cookie to the client. WebSocket cannot send cookies to clients, so the session must be created beforehand in an HTTP route. Once the session exists, it can be modified in the WebSocket handlers, and as long as you use server-side sessions the changes you made will be shared with other requests made by the client.
