### ISSUE TITLE
flask-socketIO unable to print data from client (Vuejs)

### ISSUE THREAD

**Issue by Ramiiyan** [miguelgrinberg/Flask-SocketIO#1496]
**flask-socketio is connected. Able to sent data to the client and able to Receive msg like this below.**

```
pcFlYMeCElBOBl4wAAAJ: Received packet MESSAGE data 2["on_publish",{"data":"connected to the SocketServer..."}]
received event "on_publish" from onPWUe7Ff172Mr18AAAK [/]
127.0.0.1 - - [11/Mar/2021 01:52:22] "←[37mPOST /socket.io/?EIO=4&transport=polling&t=NWTpVpR&sid=pcFlYMeCElBOBl4wAAAJ HTTP/1.1←[0m" 200 -
```
but the defined function isn't working. I'm unable to print the received data.
```
@socketIo.on('on_publish')
def handle_publish(json_str):
    data = json.loads(json_str)
    print("Received data from user : " + data) 
```
Thanks in Advance.

**Comment by miguelgrinberg** [comment]
There isn't much I can tell you with an incomplete code. The problem is not in the code you are showing me as far as I can see.

**Comment by Ramiiyan** [comment]
Sorry for the inconvenience. This is the flask app I have.
```
from flask import Flask
import eventlet
from engineio.payload import Payload
from flask_socketio import SocketIO
eventlet.monkey_patch()
app = Flask(__name__)

Payload.max_decode_packets = 50
socketIo = SocketIO(app, cors_allowed_origins="*", engineio_logger=True, logger=True)

@socketIo.on('connect')
def handle_socket_connection():
    print('Client is connected.')
    socketIo.emit('mqtt_message', data='connected')

@socketIo.on('on_publish')
def handle_publish(json_str):
    print("RECEIVED !!!")
    data = json.loads(json_str)
    print("Received data from user : " + data) 

@socketIo.on('unsubscribe_all')
def handle_unsubscribe_all():
    mqtt.unsubscribe_all()

if __name__ == '__main__':
    socketIo.run(app=app, debug=True)
```
I'm Using socketio-client in Vuejs.

 ```
created() { 
      this.connectWebsocket();
    },
    beforeDestroy() {
      this.disconnectWebsocket(); 
    },
    computed:{
      passChanges:function(){
        this.$socket.emit('on_publish', {data: 'connected to the SocketServer...'});
        console.log(msg);
        return msg;
      },
    },
    methods: {
      connectWebsocket() { 
          this.$socket.on('mqtt_message', (message) => { 
          console.log(message);
          console.log(message.payload);
          if (message.payload) {
            this.message = message.payload;
          } 
        });
      }, 
      disconnectWebsocket() {
        if (this.$socket) {
          this.$socket.emit('unsubscribe_all');
          this.$socket.disconnect();
        }
      } 
    }

```
When Server emit() the data to the Client it's working.
When Client emit() the data to the Server, data showing in Logger, but  `handle_publish()` function is not Receiving the data.

```
(venv) D:\MY FYP Local - Backend\fyp-flask-app>flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Server initialized for threading.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

Me7rZ5-dJgMOW6LHAAAA: Sending packet OPEN data {'sid': 'Me7rZ5-dJgMOW6LHAAAA', 'upgrades': [], 'ping
Timeout': 5000, 'pingInterval': 25000}
127.0.0.1 - - [11/Mar/2021 05:41:19] "←[37mGET /socket.io/?EIO=4&transport=polling&t=NWUdvXY HTTP/1.
1←[0m" 200 -
Me7rZ5-dJgMOW6LHAAAA: Received packet MESSAGE data 0
Me7rZ5-dJgMOW6LHAAAA: Sending packet MESSAGE data 0{"sid":"kOltkqF4FwTc_E_fAAAB"}
127.0.0.1 - - [11/Mar/2021 05:41:19] "←[37mPOST /socket.io/?EIO=4&transport=polling&t=NWUdvcT&sid=Me
7rZ5-dJgMOW6LHAAAA HTTP/1.1←[0m" 200 -
127.0.0.1 - - [11/Mar/2021 05:41:19] "←[37mGET /socket.io/?EIO=4&transport=polling&t=NWUdvcU&sid=Me7
rZ5-dJgMOW6LHAAAA HTTP/1.1←[0m" 200 -
Me7rZ5-dJgMOW6LHAAAA: Received packet MESSAGE data 2["on_publish",{"data":"connected to the SocketSe
rver..."}]
received event "on_publish" from kOltkqF4FwTc_E_fAAAB [/]
127.0.0.1 - - [11/Mar/2021 05:41:24] "←[37mPOST /socket.io/?EIO=4&transport=polling&t=NWUdwli&sid=Me
7rZ5-dJgMOW6LHAAAA HTTP/1.1←[0m" 200 -
Me7rZ5-dJgMOW6LHAAAA: Received packet MESSAGE data 2["on_publish",{"data":"connected to the SocketSe
rver..."}]
received event "on_publish" from kOltkqF4FwTc_E_fAAAB [/]
127.0.0.1 - - [11/Mar/2021 05:41:24] "←[37mPOST /socket.io/?EIO=4&transport=polling&t=NWUdwqr&sid=Me
7rZ5-dJgMOW6LHAAAA HTTP/1.1←[0m" 200 -
Me7rZ5-dJgMOW6LHAAAA: Received packet MESSAGE data 2["on_publish",{"data":"connected to the SocketSe
rver..."}]

```

**Comment by miguelgrinberg** [comment]
You are mixing threading and eventlet modes. Run your application by starting your script, `flask run` is for Flask, not for Socket.IO.

**Comment by Ramiiyan** [comment]
Thank you for the quick reply  @miguelgrinberg 
I tried with starting the script as you said. still, I get the same output. and my method is still not working.
```
Server initialized for eventlet.
 * Restarting with stat
16 Received CONNACK (0, 0)
16 Sending SUBSCRIBE (d0, m1) [(b'tester2/tesingdev2/v3/common', 0)]
16 Received SUBACK
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: 285-828-252
(17316) wsgi starting up on http://127.0.0.1:5000
(17316) accepted ('127.0.0.1', 49735)
h29ifPJ7_9Uy9lEdAAAA: Sending packet OPEN data {'sid': 'h29ifPJ7_9Uy9lEdAAAA', 'upgrades': ['websocket'], 'pingTimeout': 5000, 'pingInterval': 25000}
127.0.0.1 - - [11/Mar/2021 18:08:42] "GET /socket.io/?EIO=4&transport=polling&t=NWXIz0i HTTP/1.1" 200 329 0.000000
h29ifPJ7_9Uy9lEdAAAA: Received packet MESSAGE data 0
h29ifPJ7_9Uy9lEdAAAA: Sending packet MESSAGE data 0{"sid":"dzje05-DHJ4cnhJYAAAB"}
127.0.0.1 - - [11/Mar/2021 18:08:42] "POST /socket.io/?EIO=4&transport=polling&t=NWXIzZ6&sid=h29ifPJ7_9Uy9lEdAAAA HTTP/1.1" 200 219 0.000997
16 Received CONNACK (0, 0)
16 Sending SUBSCRIBE (d0, m1) [(b'tester2/tesingdev2/v3/common', 0)]
127.0.0.1 - - [11/Mar/2021 18:08:42] "GET /socket.io/?EIO=4&transport=polling&t=NWXIzZM&sid=h29ifPJ7_9Uy9lEdAAAA HTTP/1.1" 200 265 0.000000
16 Received SUBACK
(17316) accepted ('127.0.0.1', 49733)
(17316) accepted ('127.0.0.1', 49742)
h29ifPJ7_9Uy9lEdAAAA: Received request to upgrade to websocket
127.0.0.1 - - [11/Mar/2021 18:08:42] "GET /socket.io/?EIO=4&transport=polling&t=NWXIzZe&sid=h29ifPJ7_9Uy9lEdAAAA HTTP/1.1" 200 233 0.289901
h29ifPJ7_9Uy9lEdAAAA: Upgrade to websocket successful
emitting event "mqtt_message" to all [/]
-EwNmLqZ0EjUR_oUAAAA: Sending packet MESSAGE data 2["mqtt_message",{"topic":"tester2/tesingdev2/v3/common","payload":"hello"}]
emitting event "mqtt_message" to all [/]
-EwNmLqZ0EjUR_oUAAAA: Received packet MESSAGE data 2["on_publish",{"data":"connected to the SocketServer..."}]
received event "on_publish" from gvtFkvsHfXmZpIhEAAAB [/]
-EwNmLqZ0EjUR_oUAAAA: Received packet MESSAGE data 2["on_publish",{"data":"connected to the SocketServer..."}]
received event "on_publish" from gvtFkvsHfXmZpIhEAAAB [/]
-EwNmLqZ0EjUR_oUAAAA: Received packet MESSAGE data 2["on_publish",{"data":"connected to the SocketServer..."}]
received event "on_publish" from gvtFkvsHfXmZpIhEAAAB [/]
```
**NOTE**: I'm using flask_mqtt as well. I think it doesn't affect any of this  Socket.io problem.

**Comment by miguelgrinberg** [comment]
I expected the problem would remain, but the previous run was not allowing WebSocket to connect. That problem is now fixed.

Now back to the main problem. In the connect handler you have a print that says "Client is connected". Why isn't that print in the output of your server? I see that the `mqtt_message` is in the log, so the function is executing, but your print is not being captured. Any chance the same happens on the other event?

**Comment by Ramiiyan** [comment]
@miguelgrinberg  yeah, it's not printing any of the events from the client-side. 
Any of the `@socketIo.on()` defined methods are not working.
I'm defining @mqtt.on_message() to handle MQTT messages.

```
@mqtt.on_message()
def handle_mqtt_message(client, userdata, message):
    data = dict(
        topic=message.topic,
        payload=message.payload.decode()
    )
    print("my MSG : " + message.payload.decode())
    socketIo.emit('mqtt_message', data=data)
```
In this method `socketIo.emit()` publishing the message and I'm receiving it from the client-side as well.
I'm working on this problem for the last 3 days. still not getting any improvement.

**Comment by Ramiiyan** [comment]
Also, I have the `@mqtt.on_connect()` defined method and it's working perfectly. I hope that's not an issue.

```
@mqtt.on_connect()
def handle_connect(client, userdata, flags, rc):
    mqtt.subscribe('tester2/tesingdev2/v3/common')
    print("mqtt Connected.")
```
output :
```
Server initialized for eventlet.
 * Restarting with stat
16 Received CONNACK (0, 0)
16 Sending SUBSCRIBE (d0, m1) [(b'tester2/tesingdev2/v3/common', 0)]
mqtt Connected.
16 Received SUBACK
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: 285-828-252
(11468) wsgi starting up on http://127.0.0.1:5000
16 Received CONNACK (0, 0)
16 Sending SUBSCRIBE (d0, m1) [(b'tester2/tesingdev2/v3/common', 0)]
mqtt Connected.
16 Received SUBACK
16 Sending PINGREQ
16 Received PINGRESP
emitting event "mqtt_message" to all [/]
emitting event "mqtt_message" to all [/]
16 Received PUBLISH (d0, q0, r0, m0), 'tester2/tesingdev2/v3/common', ...  (5 bytes)
my MSG : hello
16 Received PUBLISH (d0, q0, r0, m0), 'tester2/tesingdev2/v3/common', ...  (5 bytes)
my MSG : hello
(11468) accepted ('127.0.0.1', 55886)
2Kp41PrQGIFzdvLxAAAA: Sending packet OPEN data {'sid': '2Kp41PrQGIFzdvLxAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
2Kp41PrQGIFzdvLxAAAA: Received request to upgrade to websocket
2Kp41PrQGIFzdvLxAAAA: Upgrade to websocket successful
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 0
2Kp41PrQGIFzdvLxAAAA: Sending packet MESSAGE data 0{"sid":"EIC5UuJ3AxvTpabpAAAB"}
16 Sending PINGREQ
16 Received PINGRESP
16 Sending PINGREQ
16 Received PINGRESP
16 Sending PINGREQ
16 Received PINGRESP
16 Sending PINGREQ
16 Received PINGRESP
16 Sending PINGREQ
16 Received PINGRESP
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 2["subscribe",{"data":"connected to the SocketServer..."}]
received event "subscribe" from EIC5UuJ3AxvTpabpAAAB [/]
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 2["subscribe",{"data":"connected to the SocketServer..."}]
received event "subscribe" from EIC5UuJ3AxvTpabpAAAB [/]
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 2["subscribe",{"data":"connected to the SocketServer..."}]
received event "subscribe" from EIC5UuJ3AxvTpabpAAAB [/]
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 2["subscribe",{"data":"connected to the SocketServer..."}]
received event "subscribe" from EIC5UuJ3AxvTpabpAAAB [/]
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 2["subscribe",{"data":"connected to the SocketServer..."}]
received event "subscribe" from EIC5UuJ3AxvTpabpAAAB [/]
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 2["subscribe",{"data":"connected to the SocketServer..."}]
received event "subscribe" from EIC5UuJ3AxvTpabpAAAB [/]
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 2["subscribe",{"data":"connected to the SocketServer..."}]
received event "subscribe" from EIC5UuJ3AxvTpabpAAAB [/]
2Kp41PrQGIFzdvLxAAAA: Received packet MESSAGE data 2["subscribe",{"data":"connected to the SocketServer..."}]
received event "subscribe" from EIC5UuJ3AxvTpabpAAAB [/]
16 Sending PINGREQ
16 Received PINGRESP
16 Sending PINGREQ
16 Received PINGRESP
16 Sending PINGREQ
16 Received PINGRESP
2Kp41PrQGIFzdvLxAAAA: Sending packet PING data None
2Kp41PrQGIFzdvLxAAAA: Received packet PONG data 
16 Sending PINGREQ
16 Received PINGRESP
16 Sending PINGREQ
```
in this output `mqtt Connected.` from `@mqtt.on_connect()` defined method. `my MSG : hello` is from  `@mqtt.on_message()` method.
I don't understand, why `@socketIo.on() ` isn't working at all.

**Comment by miguelgrinberg** [comment]
This log message comes from your server:

    emitting event "mqtt_message" to all [/]

This matches an emit call that you have in your connect handler. You claim that the handler does not run, but this says otherwise. Don't you think you have a problem with your print statements more than with Socket.IO?

**Comment by Ramiiyan** [comment]
@miguelgrinberg 
In `@mqtt.on_connect()` method, I have a print statement. and it's working. Within the `SocketIo.on()` it's not working.

**Comment by Ramiiyan** [comment]
@miguelgrinberg , this `emitting event "mqtt_message" to all [/]` is it from `@mqtt.on_message()` defined method. as I mentioned before.
I'm following this documentation [here](https://flask-mqtt.readthedocs.io/en/latest/usage.html#interact-with-socketio).

**Comment by miguelgrinberg** [comment]
I'm sorry, but it is impossible for me to diagnose your problem with a partial application. As I said before, all the code that you are showing me appears to be okay, but since I cannot test it because it is incomplete, I can't really do anything more.

Event handlers do work. All you need to do is try the examples in this repository to confirm. Something in your application isn't right. If you are editing the code to be simpler when you show it here, then you may also be inadvertently hiding the problem.

**Comment by Ramiiyan** [comment]
Thank You for your replies. @miguelgrinberg 
Do have any good updated example that Includes with Flask Mqtt and SocketIo?

**Comment by Ramiiyan** [comment]
I'm sorry for the inconvenience code.
here is the flask app main code. [here](https://github.com/Ramiiyan/fyp-flask-app/blob/main/app.py)
here is the vuejs `main.js`  code is [here](https://github.com/Ramiiyan/my-fyp-vue/blob/main/src/main.js).
used the SocketIo-client in [here](https://github.com/Ramiiyan/my-fyp-vue/blob/main/src/components/HelloWorld.vue).

**Comment by Ramiiyan** [comment]
it's Working, When I remove `evenlet` from my project, it's working perfectly.
Thank you @miguelgrinberg for your support. Have a nice day. 🙌🙌
